databases:
  - name: lengushuru-bugetApp
    databaseName: lengushuru_bugetapp
    user: lengushuru_bugetapp_user

services:
  - type: web
    name: lengushuru1
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lengushuru-bugetapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false